ALTER TABLE commande ALTER COLUMN mode_paiement DROP NOT NULL;

ALTER TABLE commande ADD COLUMN nom VARCHAR(20);
ALTER TABLE commande ADD COLUMN prenom VARCHAR(20);
ALTER TABLE commande ADD COLUMN telephone VARCHAR(20);
ALTER TABLE commande ADD COLUMN email VARCHAR(50);

ALTER TABLE commande ALTER COLUMN nom SET NOT NULL;
ALTER TABLE commande ALTER COLUMN prenom SET NOT NULL;
ALTER TABLE commande ALTER COLUMN telephone SET NOT NULL;
ALTER TABLE commande ALTER COLUMN email SET NOT NULL;
