ALTER TABLE IF EXISTS utilisateur ADD COLUMN IF NOT EXISTS type_utilisateur VARCHAR(20);

ALTER TABLE utilisateur ALTER COLUMN email SET DATA TYPE VARCHAR(100);

UPDATE utilisateur
SET type_utilisateur = 'NORMAL'
WHERE type_utilisateur IS NULL;


DELETE FROM suivi_client;
-- Start a transaction to be safe
BEGIN;

-- 1️⃣ Temporarily allow manual ID updates
ALTER TABLE utilisateuranonyme
ALTER COLUMN id SET GENERATED BY DEFAULT;

-- 2️⃣ Compute a safe id_offset
-- Get max ID from parent table
-- (Replace 0 with actual value or compute dynamically)
-- Example: MAX(id) in utilisateur = 1000
-- MAX(id) in utilisateuranonyme = 50
-- id_offset = 1000 + 50 = 1050
-- You can also compute dynamically:

DO $$
DECLARE
    max_utilisateur BIGINT;
    max_anonymous BIGINT;
    id_offset BIGINT;
BEGIN
    SELECT MAX(id) INTO max_utilisateur FROM utilisateur;
    SELECT MAX(id) INTO max_anonymous FROM utilisateuranonyme;
    id_offset := max_utilisateur + max_anonymous;

    -- 3️⃣ Update anonymous IDs safely
    UPDATE utilisateuranonyme
    SET id = id + id_offset;
END $$;

-- 4️⃣ Insert anonymous users into parent table
INSERT INTO utilisateur (id, email, type_utilisateur)
SELECT
    id,
    session_token || '@temposphere.tn',
    'ANONYMOUS'
FROM utilisateuranonyme;

-- 4. Fix sequence
SELECT setval('utilisateur_id_seq', (SELECT MAX(id) FROM utilisateur) + 1);

-- 5️⃣ Restore GENERATED ALWAYS
ALTER TABLE utilisateuranonyme
ALTER COLUMN id SET GENERATED ALWAYS;

-- Commit transaction
COMMIT;