databaseChangeLog:
  - changeSet:
      id: 1
      author: postgres
      changes:
        - sqlFile:
            path: classpath:/db/changelog/1.7.0/scripts/add_product_statut.sql
            relativeToChangelogFile: false
            splitStatements: true
            stripComments: true



